tasks/email_task/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('v1/calulate',views.display_result,name="calculate"),
]

tasks/email_task/app1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name="home"),
    path('signup/',views.signup,name="signup"),
    path('login/',views.login,name="login"),
    path('logout/',views.user_logout,name="logout"),
]

tasks/email_task/email_task/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('api/',include('api.urls')),
]

tasks/email_task/api/models.py
from django.db import models

# Create your models here.

tasks/email_task/app1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

class User(AbstractUser):
    email = models.EmailField(max_length=254, unique=True)
    phone = PhoneNumberField()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

tasks/email_task/app1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserForm(UserCreationForm):
    class Meta():
        model = User
        fields = ['email','phone','password1','password2']

tasks/email_task/api/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.

def getpower(x,n):
    a = 1
    for i in range(1,n+1):
        a = a*x
    print(a)
    return a

def calculate(x,n):
    if n == 1:
        return (1/getpower(x,1))
    else:
        return calculate(x,n-1) + (1/getpower(x,n))


@login_required
def display_result(request):
    ans = None
    if request.method == "POST":
        x = request.POST.get("x")
        n = request.POST.get("n")

        ans = calculate(int(x),int(n))


    return render(request,'api/calculate.html',{'ans':ans})

tasks/email_task/app1/views.py
from django.shortcuts import render, redirect
from .models import User
from .forms import UserForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
# Create your views here.

def home(request):
    return render(request,'app1/index.html',{})

def signup(request):
    registered = False
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            registered = True

        else:
            print(form.errors)
    else:
        form = UserForm()
    return render(request,'app1/signup.html',{'form':form,'registered':registered})

def login(request):
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(email=email,password=password)

        if user:
            if user.is_active:
                auth_login(request,user)
                return HttpResponseRedirect(reverse('home'))

            else:
                return HttpResponse("Account not active")

        else:
            print("Invalid details")
            return redirect('login')

    else:
        return render(request,'app1/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

tasks/email_task/templates/api/calculate.html
{% extends 'app1/base.html' %}
{% block content %}

<div class="container bg-light p-5">

  {% if ans %}
  <h1>Answer is {{ ans }}</h1>
  {% else %}
  <h1>Calculator for Question 5</h1>

  <form method="post">
    {% csrf_token %}
    <div class="form-group m-2">
      <label for="inputx">Enter value of X:</label>
      <input type="number" class="form-control" name="x" id="inputx" placeholder="Enter value of X">
    </div>
    <div class="form-group m-2">
      <label for="inputn">Enter value of N:</label>
      <input type="number" class="form-control" name="n" id="inputn" placeholder="Enter value of N">
    </div>
    <button type="submit" class="btn btn-primary m-2">Submit</button>

  </form>

  {% endif %}

  </div>

{% endblock %}

tasks/email_task/templates/app1/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>New App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav  mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'api:calculate' %}">Calculate</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="">{{ user.email }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'signup' %}">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}

  </body>
</html>

tasks/email_task/templates/app1/index.html
{% extends 'app1/base.html' %}
{% block content %}

<div class="container bg-light p-5">
  <h1>Welcome to Home Page!</h1>
</div>

{% endblock %}

tasks/email_task/templates/app1/login.html
{% extends 'app1/base.html' %}
{% block content %}

<div class="container bg-light p-5">

    <h1>Login</h1>

    <form method="post">
      {% csrf_token %}
    <div class="form-group m-2">
      <label for="exampleInputEmail1">Email</label>
      <input type="email" class="form-control" name="email" placeholder="Enter Your Email">
    </div>
    <div class="form-group m-2">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
    </div>
  <button type="submit" class="btn btn-primary m-2">Login</button>
</form>

  </div>

{% endblock %}

tasks/email_task/templates/app1/signup.html
{% extends 'app1/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container bg-light p-5">
  {% if registered %}
  <h1>Account Created Successfully!</h1>
  {% else %}

  <h1>Sign Up!</h1>

  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit" class="btn btn-primary">
  </form>

  {% endif %}
</div>

{% endblock %}